branches:
  only:
    - master
cache:
  bundler: true
language: ruby
rvm:
- 2.1.2
before_install:
  - travis_retry sudo wget https://s3.amazonaws.com/pd-public-files/downloads/zookeeper-345.sh
  - sudo chmod +x zookeeper-345.sh
  - sudo ./zookeeper-345.sh $TRAVIS_BUILD_DIR
before_script:
  - bundle exec rake db:setup
